# Generated by Django 6.0.2 on 2026-03-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_image_artist_user_creation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='artist_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
