# Generated by Django 6.0.2 on 2026-03-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_dimensions_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('terracotta', 'Terracotta'), ('metal', 'Metal'), ('glassart', 'Glass Art'), ('premium', 'Premium'), ('photography', 'Photography'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
